apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mwt1xcduv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mwt1xcduv-python 
  name: mwt1xcduv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mwt1xcduv-python 
